name: DiscordBridge
version: ${project.version}
description: ${project.description}

author: Jacob Gillespie
website: ${project.url}

loadbefore: [SpaceBukkit, RemoteToolkitPlugin]

main: gg.obsidian.discordbridge.Plugin

permissions:
  discordbridge.reload:
    description: Reload the Discord Bridge
    default: op

commands:
  discord:
    description: Reload the Discord Bridge
    usage: /discord reload
